package com.braveheart.gestao_ns_api.service.dto;

import java.util.UUID;

/**
 * Data Transfer Object (DTO) that represents the information sent
 * by the Supabase webhook when a new user is created.
 *
 * We use a Java 'record' because it's a modern and concise way to create
 * immutable classes that only serve to hold data.
 *
 * @param id The user's UUID generated by Supabase Auth.
 * @param email The user's email.
 */
public record UserWebhookDto(
        UUID id,
        String email
) {}